from __future__ import annotations

from dataclasses import asdict
from pathlib import Path
from typing import Any

import pandas as pd

from amce.config import PipelineConfig, load_config
from amce.data import (
    DataProvider,
    YFinanceDataProvider,
    add_lagged_features,
    add_rolling_features,
    load_base_frame,
    prepare_data_pipeline,
)
from amce.features import (
    compute_feature_frame,
    feature_registry_version,
    generate_alpha_library,
    validate_feature_frame,
)
from amce.labels import add_targets
from amce.reporting import persist_run_artifacts
from amce.types import BacktestResult, ValidationReport
from amce.validation import run_walk_forward_validation


def _resolve_provider(provider: DataProvider | None, cfg: PipelineConfig) -> DataProvider:
    if provider is not None:
        return provider
    return YFinanceDataProvider(auto_adjust=cfg.data.auto_adjust)


def run_pipeline(
    config: PipelineConfig | dict[str, Any] | str | Path | None = None,
    provider: DataProvider | None = None,
) -> ValidationReport:
    cfg = load_config(config)
    data_provider = _resolve_provider(provider, cfg)

    base_raw = load_base_frame(data_provider, cfg.data)
    base, processing_report = prepare_data_pipeline(base_raw)

    feature_frame = compute_feature_frame(base, include_categories=cfg.features.include_categories)

    alpha_added = 0
    if cfg.features.use_expanded_alpha_library:
        alpha_df, alpha_cols = generate_alpha_library(base)
        new_cols = [c for c in alpha_cols if c not in feature_frame.data.columns and c in alpha_df.columns]
        if new_cols:
            feature_frame.data = pd.concat([feature_frame.data, alpha_df[new_cols]], axis=1)
        feature_frame.feature_columns.extend(new_cols)
        alpha_added = len(new_cols)

    context_added = 0
    context_cols = [c for c in ["Risk", "Safe", "VIX", "Yield"] if c in feature_frame.data.columns]
    if cfg.features.enable_lagged_context and cfg.features.lag_days:
        before = set(feature_frame.data.columns)
        feature_frame.data = add_lagged_features(feature_frame.data, context_cols, cfg.features.lag_days)
        new_cols = [c for c in feature_frame.data.columns if c not in before]
        feature_frame.feature_columns.extend(new_cols)
        context_added += len(new_cols)

    if cfg.features.enable_rolling_context and cfg.features.rolling_windows:
        before = set(feature_frame.data.columns)
        feature_frame.data = add_rolling_features(feature_frame.data, context_cols, cfg.features.rolling_windows)
        new_cols = [c for c in feature_frame.data.columns if c not in before]
        feature_frame.feature_columns.extend(new_cols)
        context_added += len(new_cols)

    feature_frame.feature_columns = list(dict.fromkeys(feature_frame.feature_columns))
    feature_frame.data = add_targets(feature_frame.data, horizon_days=cfg.features.target_horizon_days)

    diagnostics = validate_feature_frame(feature_frame)
    report = run_walk_forward_validation(feature_frame, cfg)

    report.summary["feature_diagnostics"] = diagnostics
    report.summary["feature_count"] = len(feature_frame.feature_columns)
    report.summary["alpha_library_added_features"] = alpha_added
    report.summary["context_added_features"] = context_added
    report.summary["data_processing"] = asdict(processing_report)

    fv = feature_registry_version()
    report.summary["feature_registry_version"] = fv

    if cfg.reporting.persist_artifacts:
        out = persist_run_artifacts(report, base, cfg, fv)
        report.artifacts_dir = out

    return report


def run_backtest(
    config: PipelineConfig | dict[str, Any] | str | Path | None = None,
    provider: DataProvider | None = None,
) -> BacktestResult:
    report = run_pipeline(config=config, provider=provider)
    oos = report.extras.get("oos_frame")
    if oos is None:
        raise ValueError("No OOS frame generated by pipeline")

    return BacktestResult(
        frame=oos,
        metrics=report.summary["strategy_metrics"],
        benchmark_metrics=report.summary["benchmark_metrics"],
    )


def run_diagnostics(
    config: PipelineConfig | dict[str, Any] | str | Path | None = None,
    provider: DataProvider | None = None,
) -> dict[str, Any]:
    report = run_pipeline(config=config, provider=provider)
    return {
        "summary": report.summary,
        "governance": report.governance,
        "regime_metrics": report.regime_metrics,
        "sensitivity": report.sensitivity,
        "fold_metrics": report.fold_metrics,
    }
